spring:
    security:
        user:
            password: "1234"
    liquibase:
        change-log: classpath:db/changelog/master.yaml
    jpa:
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: fa
        password: fa

jwt:
    secret: "zdtasdasd4324s(/&/sd"
    expiration: 3600000
    refreshExpiration: 604800000